cifar100_labels_descriptions = {
    "apple": "A round fruit with a red or green skin, commonly eaten raw or cooked.",
    "aquarium_fish": "A variety of colorful fish species kept in home or public aquariums.",
    "baby": "A very young human, typically between birth and two years old.",
    "bear": "A large mammal with thick fur, known for its omnivorous diet and powerful build.",
    "beaver": "A large, semi-aquatic rodent known for building dams and lodges.",
    "bed": "A piece of furniture for sleeping or resting, typically with a mattress and frame.",
    "bee": "A flying insect known for its production of honey and role in pollination.",
    "beetle": "A type of insect characterized by its hard forewings and often robust body.",
    "bicycle": "A two-wheeled vehicle powered by pedals, used for transportation or recreation.",
    "bottle": "A container with a neck and stopper, used for holding and preserving liquids.",
    "bowl": "A round, deep dish, wider than it is tall, used for holding food or liquids.",
    "boy": "A young male human, typically between infancy and adolescence.",
    "bridge": "A structure built to span a physical obstacle, such as a body of water or a valley.",
    "bus": "A large motor vehicle carrying passengers by road, and designed to operate on a fixed route.",
    "butterfly": "A mainly diurnal insect with large, often brightly colored wings and an elongated body.",
    "camel": "A large, long-necked, hump-backed mammal of the genus Camelus, found in deserts.",
    "can": "A metal container for preserving and storing food, typically cylindrical and sealed.",
    "castle": "A large fortified building or group of buildings, often found in historical or medieval settings.",
    "caterpillar": "The larval stage of a butterfly or moth, characterized by a soft, cylindrical body.",
    "cattle": "A domesticated bovine animal, raised for its meat, milk, or labor.",
    "chair": "A piece of furniture with a back and four legs, used for seating.",
    "chimpanzee": "A primate, similar to a gorilla but with a smaller stature and more slender build.",
    "clock": "An instrument for measuring, keeping, and indicating time.",
    "cloud": "A visible mass of water droplets or ice crystals in the atmosphere.",
    "cockroach": "A type of insect with a flat body, typically found in dark and damp places.",
    "couch": "A long upholstered seat, typically with a back and arms, for more than one person.",
    "crab": "A crustacean with a short, broad carapace and five pairs of legs, often eaten as food.",
    "crocodile": "A large, semi-aquatic reptile with a long mouth and strong, saw-like teeth.",
    "cup": "A small, round container used for drinking, often made of ceramic, glass, or plastic.",
    "dinosaur": "An extinct terrestrial reptile of the Mesozoic era, often characterized by large size.",
    "dolphin": "A highly intelligent marine mammal known for its playful behavior and acrobatics.",
    "elephant": "A large mammal with a long trunk, large ears, and powerful tusks.",
    "flatfish": "A type of fish with a flattened body, typically found on the ocean floor.",
    "forest": "A large area covered chiefly with trees and undergrowth.",
    "fox": "A small to medium-sized carnivorous mammal with a pointed snout and thick fur.",
    "girl": "A young female human, typically between infancy and adolescence.",
    "hamster": "A small rodent with a short tail and large cheeks, often kept as a pet.",
    "house": "A building for human habitation, typically having at least one story and serving as a dwelling.",
    "kangaroo": "A large marsupial from Australia, known for its powerful hind legs and long tail.",
    "keyboard": "A computer input device consisting of a panel of buttons, each producing a different symbol or character.",
    "lamp": "A device for giving light, often with a shade or cover to direct the light.",
    "lawn_mower": "A machine used to cut grass on lawns, typically powered by an engine or electricity.",
    "leopard": "A large, spotted wild cat, similar to a lion but smaller and more agile.",
    "lion": "A large, strong, mane-haired wild animal of the cat family, found in Africa and Asia.",
    "lizard": "A reptile of a type that typically has four legs and a long tail.",
    "lobster": "A sea creature with a hard shell, ten legs, and two large, clawed pincers.",
    "man": "An adult male human.",
    "maple_tree": "A type of tree known for its palmate leaves, which turn red or yellow in the fall.",
    "motorcycle": "A two- or three-wheeled motor vehicle, often used for transportation or sport.",
    "mountain": "A large natural elevation of the earth's surface, typically steeper than a hill.",
    "mouse": "A small rodent with a pointed snout and large ears, often found in homes.",
    "mushroom": "A fungi with a stem and a cap, often used as food or in traditional medicine.",
    "oak_tree": "A type of tree or shrub of the genus Quercus, known for its hard, durable wood.",
    "orange": "A round citrus fruit with a tough bright reddish-yellow rind and juicy, acidic flesh.",
    "orchid": "A flower with a unique, often intricate structure, known for its beauty and variety.",
    "otter": "A carnivorous mammal with a streamlined body, webbed feet, and a thick fur, found in water environments.",
    "palm_tree": "A tree with a slender, columnar trunk and a tuft of large, ribbed, fan-shaped leaves at the top.",
    "pear": "A fruit produced by trees of the genus Pyrus, similar to an apple but with a narrower neck.",
    "pickup_truck": "A light motor vehicle with an open-top rear cargo area, often used for transporting goods.",
    "pine_tree": "A type of tree with needle-like leaves and cones, often found in forests.",
    "plain": "A large area of flat land, often used for agriculture or wildlife habitat.",
    "plate": "A flat dish, typically circular and made of ceramic, used for holding food.",
    "poppy": "A plant with red, orange, or white flowers, often associated with remembrance.",
    "porcupine": "A rodent covered with sharp quills, found in forests and deserts.",
    "possum": "A marsupial with a pointed snout, found in Australia, North America, and South America.",
    "rabbit": "A small mammal with long ears, short tail, and woolly fur, often kept as a pet.",
    "raccoon": "A nocturnal mammal with a bushy tail and masked face, known for its dexterity.",
    "ray": "A cartilaginous fish with expanded pectoral fins that form a flat, disk-like body.",
    "road": "An open space with a surface suitable for the passage of vehicles, typically with a solid edge.",
    "rocket": "A vehicle, missile, or similar object that is propelled by the ejected mass of exhaust gases.",
    "rose": "A woody perennial of the genus Rosa, with flowers that are typically red but can be white or pink.",
    "sea": "A large body of salt water that covers most of the Earth's surface.",
    "seal": "characterized by their streamlined bodies, external earless appearance, and the ability to swim with their limbs.",
    "shark": "A type of fish with a cartilaginous skeleton, known for its sharp teeth and powerful swimming ability.",
    "shrew": "A small mammal with a long, pointed snout, known for its agility and insectivorous diet.",
    "skunk": "A small, black and white mammal that can spray a strong-smelling fluid from glands near its rear.",
    "skyscraper": "A very tall, continuous building or tower, typically found in cities.",
    "snail": "A creature with a spiral shell into which it can retreat, typically moving slowly on a flat, muscular foot.",
    "snake": "A legless reptile with a long, slender body and scales, found in various environments.",
    "spider": "An arachnid with eight legs, known for spinning webs to catch prey.",
    "squirrel": "A smallor medium-sized rodent that is active during the day and has a bushy tail.",
    "streetcar": "A rail vehicle that runs on tracks in urban streets, used for public transportation.",
    "sunflower": "A plant with a large, round flower head that resembles the sun, often with yellow petals.",
    "sweet_pepper": "A bell-shaped or elongated fruit of various colors, used in cooking for its mild flavor.",
    "table": "A piece of furniture with a flat surface supported by legs, used for working at, eating, or serving food on.",
    "tank": "A large, armored fighting vehicle, carrying guns.",
    "telephone": "An instrument used for transmitting and receiving telephone calls.",
    "television": "An electronic device that receives television signals and displays them on a screen.",
    "tiger": "A large, carnivorous feline found in Asia, known for its orange coat with black stripes.",
    "tractor": "A wheeled vehicle, typically with a large engine at the front, used in agriculture for pulling or pushing heavy loads.",
    "train": "A series of connected vehicles moving along a railway, powered by locomotives or drawn by horses.",
    "trout": "A freshwater fish with dark spots on a greenish or brownish background.",
    "tulip": "A plant with a bulb that produces large, cup-shaped flowers with three petals and three sepals.",
    "turtle": "A reptile with a protective shell, living on land or in water.",
    "wardrobe": "A piece of furniture with shelves and hanging space for clothes, often with doors.",
    "whale": "A large marine mammal with a streamlined body and a blowhole on top of its head.",
    "willow_tree": "A type of tree with long, slender branches and narrow, pointed leaves, often found near water.",
    "wolf": "A wild canine with a thick coat of fur, known for living in packs and hunting in groups.",
    "woman": "An adult human female.",
    "worm": "typically with a long, cylindrical, and legless body."
    }


cifar100_labels = ['apple', 'aquarium_fish', 'baby', 'bear', 'beaver', 'bed', 'bee', 'beetle', 'bicycle', 'bottle', 'bowl', 
                   'boy', 'bridge', 'bus', 'butterfly', 'camel', 'can', 'castle', 'caterpillar', 'cattle', 'chair', 'chimpanzee', 
                   'clock', 'cloud', 'cockroach', 'couch', 'crab', 'crocodile', 'cup', 'dinosaur', 'dolphin', 'elephant', 
                   'flatfish', 'forest', 'fox', 'girl', 'hamster', 'house', 'kangaroo', 'keyboard', 'lamp', 'lawn_mower', 
                   'leopard', 'lion', 'lizard', 'lobster', 'man', 'maple_tree', 'motorcycle', 'mountain', 'mouse', 'mushroom', 
                   'oak_tree', 'orange', 'orchid', 'otter', 'palm_tree', 'pear', 'pickup_truck', 'pine_tree', 'plain', 'plate', 
                   'poppy', 'porcupine', 'possum', 'rabbit', 'raccoon', 'ray', 'road', 'rocket', 'rose', 'sea', 'seal', 'shark', 
                   'shrew', 'skunk', 'skyscraper', 'snail', 'snake', 'spider', 'squirrel', 'streetcar', 'sunflower', 
                   'sweet_pepper', 'table', 'tank', 'telephone', 'television', 'tiger', 'tractor', 'train', 'trout', 
                   'tulip', 'turtle', 'wardrobe', 'whale', 'willow_tree', 'wolf', 'woman', 'worm']

if __name__ == "__main__":
    print(len(cifar100_labels_descriptions))
    for i in cifar100_labels:
        try:
            print(cifar100_labels_descriptions[i])
        except:
            print(i, "--------")
            continue
    print(len(cifar100_labels))
