model:
  model_name: (CLIP)resnet-18-(dao2)-a       # Ablation studies are performed to verify the output layer's features-1
  group_name: 1-(CLIP)resnet18-classifier
  learning_rate: 0.001
  weight_decay: 1e-4
  optimizer: Adam 
  cuda: True
  clip_model: openai/clip-vit-base-patch32     # Only this specific CLIP model is supported for now
  num_epochs: 120                              # training epochs
  featureAlign: 128
  prompt: coarse                               # [coarse, fine] 

dataset:
  name: cifar100                               # dataset name 
  num_classes: 100
  dataset_loaction: ./data
  batch_size: 512

save_train_log:
  train_train_location: ./log                  # Output directories: img/, txt/, save/

save_model_pth:
  save_model_pth_location: ./log               # Model save path