model:
  model_name: WRN-28-10                        # Experiments on baseline network models
  group_name: 3-WRN-28-10-base      
  learning_rate: 0.1
  weight_decay: 1e-4
  optimizer: SGD 
  cuda: True
  num_epochs: 150
  else: model-base-dropout(0.3) scheduler(lr)

dataset:
  name: cifar100
  num_classes: 100
  dataset_loaction: ./data
  batch_size: 512

save_train_log:
  train_train_location: ./log      

save_model_pth:
  save_model_pth_location: ./log  